# -*- coding: utf-8 -*-
"""AsmitaTamang.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YsjTeVweRLELK0QT4Cs9B25n1HRkWda2
"""

from sklearn.model_selection import cross_val_score
import pandas as pd
import math
from sklearn import datasets, model_selection, metrics
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, KFold
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, Normalizer, LabelEncoder, OrdinalEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, roc_auc_score, ConfusionMatrixDisplay, accuracy_score,f1_score
import seaborn as sns

# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "developer_burnout_dataset_7000.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "asifxzaman/developer-burnout-prediction-dataset7000-samples",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df.head()
df.info()

df.dropna(axis=0, inplace=True)
df.info()

df.drop_duplicates(inplace=True)
df.info()

label=df['burnout_level']

features=df[["age", "experience_years", "daily_work_hours", "sleep_hours", "caffeine_intake", "bugs_per_day", "commits_per_day", "meetings_per_day", "screen_time",
"exercise_hours", "stress_level"]]

for col in features.columns:
    sns.boxplot(x=label, y=features[col])
    plt.xlabel("Burnout Level")
    plt.ylabel(col)
    plt.title(col)
    plt.show()

features.groupby(label)[["age", "experience_years", "daily_work_hours", "sleep_hours", "caffeine_intake", "bugs_per_day", "commits_per_day", "meetings_per_day", "screen_time",
"exercise_hours", "stress_level"]].mean().plot(kind="bar",  width=0.85, color=[
        "steelblue", "orange", "green", "red",
        "purple", "brown", "pink", "gray",
        "royalblue", "cyan", "black"
    ])
plt.xlabel("Burnout Level")
plt.ylabel("Average Value")
plt.title("Average Values by Burnout Level")
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

#features selected after looking at visuals
features=df[['stress_level','screen_time', 'meetings_per_day','bugs_per_day','daily_work_hours','sleep_hours','caffeine_intake']]

x_train, x_test, y_train, y_test= model_selection.train_test_split(features, label, test_size=0.2, random_state=42)

#Decision Tree Model

dt = DecisionTreeClassifier(random_state=42)

dt.fit(x_train, y_train)
pred=dt.predict(x_test)

dt.feature_importances_

f1 = f1_score(y_test,pred,average='macro')
print("F1-score:", f1)
ConfusionMatrixDisplay.from_estimator(dt, x_test, y_test)

#Logistic Regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

f1 = f1_score(y_test, y_pred, average='macro')
print("F1-score:", f1)


ConfusionMatrixDisplay.from_estimator(model, x_test, y_test)

#KN neighbors
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)


f1 = f1_score(y_test, y_pred, average='macro')
print("F1-score:", f1)
ConfusionMatrixDisplay.from_estimator(knn, x_test, y_test)

#features without "stress_level"

features=df[['screen_time', 'meetings_per_day','bugs_per_day','daily_work_hours','sleep_hours','caffeine_intake']]

x_train, x_test, y_train, y_test= model_selection.train_test_split(features, label, test_size=0.2, random_state=42)

#Decision Tree
dt = DecisionTreeClassifier(random_state=42)

dt.fit(x_train, y_train)
dt_pred=dt.predict(x_test)

print(dt.feature_importances_)

f1 = f1_score(y_test, y_pred, average='macro')
print("F1-score:", f1)


ConfusionMatrixDisplay.from_estimator(dt, x_test, y_test)

#Logistic Regression
model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)

y_pred= model.predict(x_test)
y_pred

f1 = f1_score(y_test, y_pred, average='macro')
print("F1-score:", f1)


ConfusionMatrixDisplay.from_estimator(model, x_test, y_test)

#KNN
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)

f1 = f1_score(y_test, y_pred, average='macro')
print("F1-score:", f1)
ConfusionMatrixDisplay.from_estimator(knn, x_test, y_test)

